#!/bin/bash

cat << EOF
BWO-0000 : Basic IPTV

This is a basic functionnal test which uses an IPTV live stream as source and
transcodes to a RTP destination.

NOTE : make sure to add all jira bug (BWO) related to this issue on the first line. By default, it should only have one. Also, make sure to add a one line description on the first line too, for the "summary" function of utilities 

EOF

#Add any required label, jenkins will assigned a node corresponding to that label string giving.
#Jenkins will still enforce all test to run on a node that can run test (FT-LTRX labelled node)
#No matter what is written in labels
#If no node can be run the test (no node with the corresponding label) the test will be desactivated.
#Jenkins allows label expression 
#ex:
#  (LABEL1&&LABEL2)||(LABEL1&&LABEL3)
#
#You should add labels to a test if said test requires some optional package or specific hardware.
#here are some labels : OPT-MSS,OPT-IDCC,OPT-Immervison
#instead of ussing GPU has a label for test using IMS, use OPT-MSS
##LABEL:

# if you need some media uncomment this :
#Be carefull to keep the medias requested are following the exact format below. Don't removed the array expand and export has a last line.
#medias=(${medias[@]} http://meduse.sherb.vantrix.com/meduse_medias/CUSTOMER/Immervision/Immervision_Lobby_Panasonic.mp4)
#export medias
#
# if you produce output, clean them before test start
rm medias/output -rf
#
# vod output need to have the output path created
#mkdir -p medias/output/rate-1

# Basic Setup
source "$(dirname ${0})/utilities"

# Use the test prologue for sanity checks
ft-prologue "${@}"

logmsg "checking if source feed udp://232.88.0.112:1236 is received"

# Check that the source feed is alive
ft-check gst-udp 232.88.0.112 1236 1
logmsg "Sanity check input port passed"

# Initialize test, launch the LTRX and begin processing
ft-setup "${@}"

# check output
ft-check wait-for-file "medias/output/rate-1/ft-rate-1_0.ts" "30"

logmsg "TEST GOOD!"

# Checks are complete, terminate the test and cleanup
ft-teardown
