#!/bin/bash

cat << EOF
LTRX-282_decrypt_mp4 : MP4 decryption support

Decrypt an mp4 with LTRX with aes-256-cbc
This test that mediainfo can analyse an encrypted mp4
Also test that LTRX can decrypt and process the encrypted mp4
Test decrypt using a key provide direclty in source.

ie : This test didn't need to connect to an Oracle server to decrypt the encryption key.

EOF


#Add any required label, jenkins will assigned a node corresponding to that label string giving.
#Jenkins will still enforce all test to run on a node that can run test (FT-LTRX labelled node)
#No matter what is written in labels
#If no node can be run the test (no node with the corresponding label) the test will be desactivated.
#Jenkins allows label expression 
#ex:
#  (LABEL1&&LABEL2)||(LABEL1&&LABEL3)
#
#You should add labels to a test if said test requires some optional package or specific hardware.
#here are some labels : OPT-MSS,OPT-IDCC,OPT-Immervison
#instead of ussing GPU has a label for test using IMS, use OPT-MSS
##LABEL:

# if you need some media uncomment this :
#Be carefull to keep the medias requested are following the exact format below. Don't removed the array expand and export has a last line.
medias=(${medias[@]} http://meduse.sherb.vantrix.com/meduse_medias/apple-green.png)
medias=(${medias[@]} http://meduse.sherb.vantrix.com/meduse_medias/VIDEO/PIXEL/mp4/h264/Mormons_ads.mp4)
export medias
#
# if you produce output, clean them before test start
rm medias/output -rf

# Basic Setup
source "$(dirname ${0})/utilities"

# Use the test prologue for sanity checks
ft-prologue "${@}"


logmsg "creation of encrypted media using openssl"
# We use the same encryption key than in the service (and same iv vector)
openssl enc -e -aes-256-cbc -in medias/Mormons_ads.mp4 -out medias/Mormons_ads.mp4.encrypted -K 000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F -iv 000102030405060708090A0B0C0D0E0F


# Initialize test, launch the LTRX and begin processing
ft-setup "${@}"

logmsg "======================================"
logmsg "Validate that service with drm entry and debug encryption key"
logmsg "work correctly."

# check output
ft-check wait-for-file "medias/output/Mormons_ads.mp4.decrypted" "20"

logmsg "basic analysis of the decrypted file"
analyser "medias/output/Mormons_ads.mp4.decrypted" &> "medias/output/analysis.txt"

logmsg "check if LTRX output file type is mp4"
ft-check grep --quiet "ContentType video/mp4" "medias/output/analysis.txt"

logmsg "TEST GOOD!"

# Checks are complete, terminate the test and cleanup
ft-teardown
